Feature/sooyong/habitlist
prography/6th_team4_ios pull request #5
Opened 2020-05-24 06:13 UTC by dev-wd

# What is PR?
- Add Moya
- Add Habit List TableView
- Coordinator is modified  

# Feature
- Moya Library 활용, 아직 통신은 되지 않지만, 새 버전에 맞게 코드 작성
- IndicatorView를 Moya Plugin에 추가하여 Network Call 시 Indicator 적용 시켜줌 (Toast_Swift Library)
- Habit List 구조 작성
- Constant, UIView Extension 추가 
- 폴더 구조 변경 

# Issues
- Navigating custom problem

리뷰부탁염ㅎㅎ

2020-05-25 07:13 UTC, sxxjxxhxxn requested changes

2020-05-25 07:13 UTC, sxxjxxhxxn commented on uso/Network/Service/HabitAPI.swift
> +
여기 포함해서 SwiftLint Warning 뜨는 곳들 고쳐주세요~

2020-05-25 07:13 UTC, sxxjxxhxxn commented on uso/Extension/IndicatorView.swift
> +        let subViewsArr = UIApplication.shared.keyWindow?.subviews
'keyWindow' was deprecated in iOS 13.0: 13부터 제대로 작동 안 할 가능성 있는 것 같아요~

2020-05-25 07:13 UTC, sxxjxxhxxn commented on uso/Cell/HabitList/ProfileCell.swift
> +    @IBOutlet weak var profileView: UIView!
작업 편의를 위해서 UIView들은 알아보기 쉽게 색을 주는 거 어떨까요? (layout() 메소드 추가)

2020-05-25 07:13 UTC, sxxjxxhxxn commented on uso/Storyboard/HabitListViewController.storyboard
> +                            <view contentMode="scaleToFill" translatesAutoresizingMaskIntoConstraints="NO" id="nde-0r-K6B">
이 UIView 왜 있는 거야? 레이아웃 맞추려고 있는건가?

2020-05-25 07:13 UTC, sxxjxxhxxn commented on uso/ViewController/SignViewController.swift
>          navigateButton.rx
처음 navigateButton을 통해서 탭바화면으로 들어가면 navigation bar (back 버튼) 가 보이고
habit list 페이지에서 plussButton (네이밍 s 2개인 거 오타지?) 을 통해서 HabitAddVC 갔다가 돌아오면 사라지네요

2020-05-25 07:13 UTC, sxxjxxhxxn commented on uso/Coordinator/MainCoordinator.swift
> +        navigationController.pushViewController(viewController, animated: true)
모달은 present로 처리해주세요~

2020-05-25 07:13 UTC, sxxjxxhxxn commented on uso/ViewModel/HabitListViewModel.swift
> +
뷰모델에 데이터 어떻게 받아올지도 얘기해보고 통일해야겠지?

2020-05-25 07:13 UTC, sxxjxxhxxn commented on uso/Network/Service/HabitAPI.swift
> +            case .sendErrorLog                  : return "inspection-error-log" // 이거 어떻게해야할지 생각해보자
sendErrorLog가 어떤 경우에 쓰이는지 알 수 있을까?

2020-05-25 07:13 UTC, Jaehooooooon commented on uso/ViewController/HabitListViewController.swift
> +extension HabitListViewController: Storyboarded, UITableViewDelegate {
tableview의 delegate 지정해줬어?

2020-05-31 13:09 UTC, dev-wd commented on uso/Network/Service/HabitAPI.swift
> +
우리 띄워서 보여주기로 약속한 부분이 SwiftLint Warning Colone 예외처리했으!

2020-05-31 13:13 UTC, dev-wd commented on uso/Storyboard/HabitListViewController.storyboard
> +                            <view contentMode="scaleToFill" translatesAutoresizingMaskIntoConstraints="NO" id="nde-0r-K6B">
그러게.. 기억이 안나네 지웠습니다~

2020-05-31 13:15 UTC, dev-wd commented on uso/ViewModel/HabitListViewModel.swift
> +
서로 다른 Struct Type을 원 스트림으로 받아오려면 Array에 Type을 따로 지정할 수 있는 방법이 있남? 이거 잘 모르겠더라... 고민해봐야될거같아. 이거 때문에 Stream 나누는건 아닌거 같은데..

2020-05-31 13:17 UTC, dev-wd commented on uso/ViewController/HabitListViewController.swift
> +extension HabitListViewController: Storyboarded, UITableViewDelegate {
수정했습니다~

2020-05-31 13:29 UTC, dev-wd commented on uso/Extension/IndicatorView.swift
> +        let subViewsArr = UIApplication.shared.keyWindow?.subviews
생유 일단 두고 추후 수정할게!

2020-06-05 01:20 UTC, merged